version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_certs:/certs/client:ro
    networks:
      - jenkins-net
    depends_on:
      - docker

  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    command: --storage-driver=overlay2
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_certs:/certs/client
      - jenkins_home:/var/jenkins_home
    networks:
      jenkins-net:
        aliases:
          - docker

volumes:
  jenkins_home:
  jenkins_certs:

networks:
  jenkins-net:

